[package]
name = "namepool"
version = "0.1.0"
edition = "2024"

[dependencies]
memchr = "2"
serde = { version = "1", features = ["derive"] }
itertools = "0.14"
parking_lot = { version = "0.12", features = ["serde"] }
